### ISSUE TITLE
Error with GET with link /auth/callback?code=bB8F2LydhxHJxhGPScJszZcc2eN0y5

### ISSUE THREAD

**Issue by makebot-help** [Terminal/discordapps.dev#81]
I was simply logging in and encountered this error.

---
URL: /auth/callback?code=bB8F2LydhxHJxhGPScJszZcc2eN0y5
METHOD: GET

```
FetchError: https://cdn.discordapp.com/avatars/275138157295435778/e12695678bfed45dd88286fbf98ed7c2.png - request to http://img.ls.terminal.ink/https://cdn.discordapp.com/avatars/275138157295435778/e12695678bfed45dd88286fbf98ed7c2.png failed, reason: connect ECONNREFUSED 198.12.71.103:80
    at ClientRequest.<anonymous> (/root/ls.terminal.ink/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:188:13)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by lepon01** [comment]
This is the fault of the Terminal.ink image server which resets itself (and breaks like discords image server)

I'll be getting a new server soon
The real big is that the callback code for oauth shouldn't appesr

**Comment by lepon01** [comment]
The img.ls.terminal.ink server is back up

**Comment by lepon01** [comment]
The server has been replaced.

**Comment by lepon01** [comment]
Thinking about it, it does raise the issue that the error message should be more useful to the end user

I'll think about making it better soon

**Comment by 7coil** [comment]
Hasn't happened in months.
